### ISSUE TITLE
why are there bare filenames in the set of document_uri records for an lti pdf assignment?

### ISSUE THREAD

**Issue by judell** [hypothesis/lti#114] opened 2017-10-05 17:01 UTC
See https://metabase.hypothes.is/question/184

**Comment by seanh** [comment] 2017-10-05 17:05
This looks like lti.hypothesislabs?

**Comment by judell** [comment] 2017-10-05 17:12
Yes, that's true. Let me find and compare an lti.hypothesis example.

**Comment by judell** [comment] 2017-10-05 17:15
https://metabase.hypothes.is/question/185

**Comment by seanh** [comment] 2017-10-05 17:19
So the problem is that one of the `DocumentURI`s is just the filename, `xyz123.pdf`? No idea, but the entire downloading and re-serving of PDF files is gone from the LTI app now, and any `DocumentURI`s created by using the LTI app are the fault of Via and the client. So closing this as an LTI issue. If the issue can be produced with the LTI app as on production right now, then it should be produceable directly in Via too.

**Closed as completed by seanh** 2017-10-05 17:19 UTC

**Comment by judell** [comment] 2017-10-05 17:28
> it should be produceable directly in Via too

Good point, I'll check. Thanks.
